services:

  mariadb:
    container_name: mcp_host_MARIADB
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql

  minio-staging:
    container_name: mcp_host_MINIO_STAGING
    image: quay.io/minio/minio:latest
    command: server /data --console-address "0.0.0.0:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/staging:/data
    restart: unless-stopped

  minio-images:
    container_name: mcp_host_MINIO_IMAGES
    image: quay.io/minio/minio:latest
    command: server /data --console-address "0.0.0.0:9002"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9002:9002"
    volumes:
      - ./data/images:/data
    restart: unless-stopped

  minio-videos:
    container_name: mcp_host_MINIO_VIDEOS
    image: quay.io/minio/minio:latest
    command: server /data --console-address "0.0.0.0:9003"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9003:9003"
    volumes:
      - ./data/videos:/data
    restart: unless-stopped