mcp_units:
  - name: MARIADB
    type: database
    role: metadata
    host: localhost
    port: 3306
    protocol: mysql

  - name: MINIO
    type: objectstore
    role: media-storage
    host: localhost
    port: 9000
    ui: http://localhost:9001
    buckets:
      - staging
      - images
      - videos